name: Sync Rules

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Converter
        run: python convert.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status -s)" ]; then
            git add dist/
            git commit -m "Auto-update rules: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected."
          fi
